apiVersion: v1
kind: Pod
metadata:
  name: cartpole-agent-a3c-resnet152-128-lr1e-4-adam-pretrained
  namespace: self-supervised-rl-minecraft
  labels:
    app.kubernetes.io/name: training-a3c-stcngurs2
spec:
  volumes:
    - name: supervised-rl-mc
      #persistentVolumeClaim:
      #  claimName: pvc-self-supervised-rl-minecraft
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - acds-gpu-01
                  - ki-srv01
                  - ki-srv02
                  - ki-srv03
                  - malea-srv02

  containers:
    - image: immortex/self-supervised-rl-minecraft:agent
      name: trainer
      imagePullPolicy: Always
      resources:
        requests:
          nvidia.com/gpu: "1"
          cpu: "1"
          memory: "16Gi"
        limits:
          nvidia.com/gpu: "1"
          cpu: "1"
          memory: "16Gi"

      ports:
        - containerPort: 8090
          name: http-agent

      volumeMounts:
        - mountPath: "/app/wandb_tmp"
          name: supervised-rl-mc
      envFrom:
        - secretRef:
            name: stcngurs-http-auth
        - secretRef:
            name: stcngurs-minio-auth
        - secretRef:
            name: stcngurs-wandb-auth
        - secretRef:
            name: stcngurs-a3c-env2
        - secretRef:
            name: stcngurs-hyperparameters-env
        - secretRef:
            name: stcngurs-hyperparameters-env-cartpole-overwrite

  restartPolicy: Never