apiVersion: v1
kind: Pod
metadata:
  name: trainer-simclr-pretrain-breakout5-naturecnn--seq4
  namespace: stable-gym
  labels:
    app.kubernetes.io/name: training-simclr-pretrain-stcngurs2 # CHANGE for each run!!!!
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - acds-gpu-01
                  #- ki-srv01
                  #- ki-srv02
                  #- ki-srv03
  containers:
    - image: immortex/self-supervised-rl-minecraft:trainer
      name: trainer
      imagePullPolicy: Always
      resources:
        requests:
          nvidia.com/gpu: "1"
          cpu: "32"
          memory: "512Gi"
        limits:
          nvidia.com/gpu: "1"
          cpu: "32"
          memory: "512Gi"

      ports:
        - containerPort: 8080
          name: http-pre2  # CHANGE for each run!!!!

      volumeMounts:
        - name: pvc-stable-gym-wandb
          mountPath: "/app/wandb_tmp"
        - name: config-dir
          mountPath: "/app/used-config"
        - name: tmp-dir
          mountPath: "/app/tmp"
      envFrom:
        - secretRef:
            name: stcngurs-http-auth
        - secretRef:
            name: stcngurs-minio-auth
        - secretRef:
            name: stcngurs-wandb-auth
        - secretRef:
            name: stcngurs-simclr-pretrain-env
        - secretRef:
            name: stcngurs-wandb-tmp-online

  volumes:
    - name: config-dir
    - name: tmp-dir
    - name: pvc-stable-gym-wandb
      #persistentVolumeClaim:
      #  claimName: pvc-stable-gym-wandb

  restartPolicy: Never