apiVersion: v1
kind: Pod
metadata:
  name: trainer-multitask-pretrain-swin-vit-depth2-cartpole
  namespace: self-supervised-rl-minecraft
  labels:
    app.kubernetes.io/name: training-multitask-pretrain-stcngurs
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  #- acds-gpu-01
                  #- ki-srv01
                  - ki-srv02
                  #- ki-srv03

  containers:
    - image: immortex/self-supervised-rl-minecraft:trainer
      name: trainer
      imagePullPolicy: Always
      resources:
        requests:
          nvidia.com/gpu: "1"
          cpu: "16"
          memory: "256Gi"
        limits:
          nvidia.com/gpu: "1"
          cpu: "64"
          memory: "256Gi"

      ports:
        - containerPort: 8080
          name: http-trainer-pr

      volumeMounts:
        - name: pvc-stable-gym-wandb
          mountPath: "/app/wandb_tmp"
        - name: config-dir
          mountPath: "/app/used-config"
      envFrom:
        - secretRef:
            name: stcngurs-http-auth
        - secretRef:
            name: stcngurs-minio-auth
        - secretRef:
            name: stcngurs-wandb-auth
        - secretRef:
            name: stcngurs-multitask-pretrain-env
        - secretRef:
            name: stcngurs-hyperparameters-env
        - secretRef:
            name: stcngurs-hyperparameters-env-multitask-pretrain-overwrite
        - secretRef:
            name: stcngurs-wandb-tmp

  volumes:
    - name: config-dir
    - name: pvc-stable-gym-wandb
      persistentVolumeClaim:
        claimName: pvc-stable-gym-wandb

  restartPolicy: Never